// Auto-generated from public/gpx folder
export const toursData = {
  vTours: [
    {
      name: 'V1',
      distance: 1.1,
      startDistance: 0.3,
      endDistance: 1.5,
    },
    {
      name: 'V2',
      distance: 1.3,
      startDistance: 0.5,
      endDistance: 1.9,
    },
    {
      name: 'V3',
      distance: 1.2,
      startDistance: 1.5,
      endDistance: 1.4,
    },
    {
      name: 'V4',
      distance: 1.2,
      startDistance: 1.6,
      endDistance: 2.8,
    },
    {
      name: 'V5',
      distance: 1.9,
      startDistance: 1.6,
      endDistance: 2.8,
    },
    {
      name: 'V6',
      distance: 1.2,
      startDistance: 2,
      endDistance: 3,
    },
    {
      name: 'V7',
      distance: 1.4,
      startDistance: 1.4,
      endDistance: 2.8,
    },
    {
      name: 'V8',
      distance: 1.8,
      startDistance: 0.3,
      endDistance: 2.2,
    },
    {
      name: 'V9',
      distance: 1.2,
      startDistance: 2.9,
      endDistance: 4.1,
    },
    {
      name: 'V10',
      distance: 2.4,
      startDistance: 2.9,
      endDistance: 3.7,
    },
    {
      name: 'V11',
      distance: 1.8,
      startDistance: 1.5,
      endDistance: 2.6,
    },
    {
      name: 'V12',
      distance: 1.5,
      startDistance: 2.5,
      endDistance: 3.3,
    },
    {
      name: 'V13',
      distance: 1.1,
      startDistance: 3,
      endDistance: 4.3,
    },
    {
      name: 'V14',
      distance: 2.4,
      startDistance: 3,
      endDistance: 3.3,
    },
    {
      name: 'V15',
      distance: 2.1,
      startDistance: 3,
      endDistance: 4,
    },
  ],
  pTours: [
    {
      name: 'P1',
      distance: 0.5,
      startDistance: 0.2,
      endDistance: 0.3,
    },
    {
      name: 'P2',
      distance: 0.7,
      startDistance: 0,
      endDistance: 0.4,
    },
    {
      name: 'P3',
      distance: 0.7,
      startDistance: 0,
      endDistance: 0.6,
    },
    {
      name: 'P4',
      distance: 0.9,
      startDistance: 0,
      endDistance: 0.8,
    },
    {
      name: 'P5',
      distance: 1.6,
      startDistance: 0,
      endDistance: 0.7,
    },
    {
      name: 'P6',
      distance: 1.5,
      startDistance: 0,
      endDistance: 0.9,
    },
    {
      name: 'P7',
      distance: 1.3,
      startDistance: 0,
      endDistance: 0,
    },
    {
      name: 'P8',
      distance: 0.8,
      startDistance: 0,
      endDistance: 0.7,
    },
    {
      name: 'P9',
      distance: 0.9,
      startDistance: 0,
      endDistance: 0.2,
    },
    {
      name: 'P10',
      distance: 0.5,
      startDistance: 0,
      endDistance: 0.2,
    },
    {
      name: 'P11',
      distance: 1.1,
      startDistance: 0,
      endDistance: 0.3,
    },
    {
      name: 'P12',
      distance: 0.7,
      startDistance: 0.9,
      endDistance: 0.6,
    },
    {
      name: 'P13',
      distance: 0.8,
      startDistance: 0.8,
      endDistance: 1,
    },
  ],
};
